name: "Deploy to AWS"

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  release-new:
    name: "Deploy to AWS"
    runs-on: ubuntu-latest

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PROD_KEY" > ~/.ssh/ssh-key.pem
          chmod 600 ~/.ssh/ssh-key.pem
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_PROD_HOST
            User $SSH_PROD_USER
            IdentityFile ~/.ssh/ssh-key.pem
            StrictHostKeyChecking no
          END
        env:
          SSH_PROD_USER: ${{ secrets.FFUT_SSH_USER }}
          SSH_PROD_KEY: ${{ secrets.FFUT_SSH_KEY }}
          SSH_PROD_HOST: ${{ secrets.FFUT_SSH_HOST }}

      - name: "Stop and Prune"
        run: ssh prod 'docker compose down && docker system prune -af'

      - name: "Start Server"
        run: ssh prod 'docker compose up -d'
