name: Default CI/CD

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build-and-test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: "Set up JDK 22"
        uses: actions/setup-java@v4
        with:
          java-version: "22"
          distribution: "temurin"
          cache: "maven"

      - name: "Package and Test"
        # Skip ProcessRunnerTest to avoid issues with GitHub Actions
        run: mvn clean package -Dtest=\!ProcessRunnerTest

  package-and-push:
    name: Push Docker Image
    runs-on: ubuntu-latest
    needs: [build-and-test]
    permissions:
      contents: read
      packages: write

    if: startsWith(github.head_ref, 'main')

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v2

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build and push"
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: ghcr.io/yurinogueira/ffut:latest
